### PR TITLE
Removing ceninusepy3 and update requirements.

### PR DESCRIPTION
**Pull request by awais786**
https://openedx.atlassian.net/browse/BOM-1662

Removing ceninusepy3
update requirements.

**Description:**

Describe in a couple of sentence what this PR adds

**JIRA:**

[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)

**Dependencies:**

List dependencies on other outstanding PRs, issues, etc.

**Merge deadline:**

List merge deadline (if any)

**Installation instructions:**

List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] @edx/arch-review (Required)
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed
- [ ] PR author is listed in AUTHORS

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:**

List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

### CODE REVIEW

**Comment by robrap** [comment]
Also, can you please get `continuous-integration/travis-ci` unstuck?  Thank you.

**Comment by awais786** [comment]
> Please confirm that your team did your own review of the upgrade changes using https://openedx.atlassian.net/wiki/spaces/TE/pages/1001521320/Python+Package+Changelogs
> 
> I will merge as soon as you confirm it is ready. Thanks.

@robrap I have updated the changelog. If you are asking about team is doing own reviews answer is Yes.

**Comment by robrap** [comment]
@awais786: I know you do your own reviews generally.  The Changelog Confluence page I sent is used to review external changelogs for dependencies that are being updated, and I was just checking that you had done that.  From the version numbers, it doesn't look like there is anything particularly noteworthy though.

Do you know what is behind the `continuous-integration/travis-ci` issue?  Is that a larger issue we are seeing elsewhere?

Good luck.

**Comment by awais786** [comment]
> @awais786: I know you do your own reviews generally. The Changelog Confluence page I sent is used to review external changelogs for dependencies that are being updated, and I was just checking that you had done that. From the version numbers, it doesn't look like there is anything particularly noteworthy though.
> 
> Do you know what is behind the `continuous-integration/travis-ci` issue? Is that a larger issue we are seeing elsewhere?
> 
> Good luck.

For `continuous-integration/travis-ci` issue its happening in this repo only right now. We have merged prs in several other repos and travis working fine there.

**Comment by robrap** [comment]
Thanks @awais786!

**Pull request merged**
