### PR TITLE
[BD-32] feat: add async feature to Hooks Extension Framework tooling

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:**

This PR allows the [Hooks Extension Framework: Pipeline](https://github.com/edx/edx-django-utils/blob/457b307d1ee1d2d3329442811254657aa3f9f8ec/edx_django_utils/hooks/pipeline.py#L12) (check out its [ADR](https://github.com/edx/edx-django-utils/blob/457b307d1ee1d2d3329442811254657aa3f9f8ec/docs/decisions/0006-hooks-tooling-pipeline.rst)) defined in [PR 110](https://github.com/edx/edx-django-utils/pull/110) to run asynchronously using celery tasks.

**JIRA:**

[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)

**Dependencies:**

**BE AWARE** This PR depends on [Hooks Extension Framework: Tooling](https://github.com/edx/edx-django-utils/pull/110)

**Merge deadline:**

None

**Installation instructions:**

List any non-trivial installation
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPi after tag-triggered build is
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:**

- [ ] Will there be a problem with adding celery? Adding it will cause other applications to crash?

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mariajgrimaldi! I've created [BLENDED-809](https://openedx.atlassian.net/browse/BLENDED-809) to keep track of it in Jira.


When this pull request is ready, tag your edX technical lead.

**Comment by regisb** [comment]
@mariajgrimaldi Is this ready for review? Please tag me whenever it is.

**Comment by mariajgrimaldi** [comment]
Hey @regisb, thanks for your reply!

Before reviewing this, please check out the thread on discuss about [Hooks Extension Framework](https://discuss.openedx.org/t/configuration-for-the-hooks-extension-framework/4527). In there, you'll find more context about this PR and PR 110.

**Comment by mariajgrimaldi** [comment]
The [discuss](https://discuss.openedx.org/t/configuration-for-the-hooks-extension-framework/4527) and [OEP](https://github.com/edx/open-edx-proposals/pull/184/) feedback has led us to remove native support for async. 

It is therefore preferable for events to follow the pattern:

> Listen on a signal and then create the async task

But that will be the responsibility of whoever writes the action.

**Pull request closed without merging**
