### PR TITLE
Bump the version for `pluggable_decorator`

### PR DESCRIPTION
**Pull request by nedbat**
Update the version number to make pluggable_decorator available to users of this repo.

### CODE REVIEW

**Comment by nedbat** [comment]
@Agrendalath let's get the version bumped.

**Comment by Agrendalath** [comment]
@nedbat, good point, thank you for handling this!

**Comment by Agrendalath** [comment]
@nedbat, could you please also create the `3.16.0` tag?

**Comment by nedbat** [comment]
There's always another step... Done.

**Comment by Agrendalath** [comment]
@nedbat, oh, I think it needs to be a release, not a tag. Cf. [the PyPi workflow](https://github.com/edx/edx-django-utils/blob/master/.github/workflows/pypi-publish.yml#L4).

**Comment by nedbat** [comment]
Sorry! Done.

**Pull request merged**
